version: '3.9'
services:
  server:
    container_name: server-container
    build: .
    ports:
      - '3000:3000'

    
  db:
    container_name: database-container
    image: postgres
    ports: 
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_DATABASE: postgres
      POSTGRES_PASSWORD: 123456


